XD_ANALYTICS: ${analytics:memory}
XD_TRANSPORT: ${transport:local}
XD_STORE: ${store:memory}
XD_HOME: ${xdHomeDir:${HOME}/dev/xd/spring-xd}
spring:
  main:
    parentSources: classpath:/META-INF/spring-xd/internal/xd-global-beans.xml

---

spring:
  profiles: adminServer
  
---

spring:
  profiles: node
  main:
    webEnvironment: false
management:
  port: 9000