XD_ANALYTICS: ${analytics:memory}
XD_TRANSPORT: ${transport:local}
XD_STORE: ${store:memory}
XD_HOME: ${xdHomeDir:${HOME}/dev/xd/spring-xd}

---

spring:
  profiles: adminServer
  
---

spring:
  profiles: node
management:
  port: 9000